# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CS4PS @ UON 2016
email: daniel.hickmott@uon.edu.au
contact: Daniel Hickmott
baseurl: "/ps-2016"

# Google services
google_analytics: UA-87991896-1


# Content Pages Paths
resources_path: "/resources"
extras_path: "/extras/"

# Day 1 Paths
day1_path: "/day1/"
scratch_path: "/day1/visualprogramming/"
robotics_path: "/day1/robotics/"
csunplugged_path: "/day1/csunplugged/"

# Day 2 Paths
day2_path: "/day2/"
appinventor_path: "/day2/appinventor/"
lessonplanning_path: "/day2/lessonplanning/"
making_path: "/day2/physicalcomputing/"
sharing_path: "/day2/sharing/"

# Build settings
markdown: kramdown
